# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nranna <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/10/18 12:19:00 by nranna            #+#    #+#              #
#    Updated: 2023/11/01 11:20:47 by nranna           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = cc
CFLAGS = -Wall -Wextra -Werror
TARGET = libft.a
SRC = libft.h ft_atoi.c ft_isalpha.c ft_isprint.c ft_memcpy.c ft_memset.c ft_strlen.c ft_isalnum.c ft_isascii.c ft_isdigit.c 
